package com.dineahead.enums;

public enum NotificationType {

    FOOD_ORDERING_OPEN,

    RESERVATION_CREATED,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELLED,
    RESERVATION_COMPLETED,

    ORDER_PLACED,
    ORDER_ACCEPTED,
    ORDER_PREPARING,
    ORDER_READY,
    ORDER_SERVED,
    ORDER_CANCELLED,

    PAYMENT_COMPLETED
}